services:
  - type: web
    name: youtube-transcript-frontend
    env: node
    plan: free
    rootDir: youtube-transcript-app
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: youtube-transcript-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://yscrpt.vercel.app 
      - key: VITE_GOOGLE_CLIENT_ID
        value: 548181107797-q318cv5b7uanogifcsf5uqitke6v0sda.apps.googleusercontent.com
      - key: VITE_GOOGLE_CLIENT_SECRET
        value: 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
      - key: VITE_INSTANTDB_APP_ID
        value: 6ffe6654-ded0-4219-9c3b-e72c666a656c

databases:
  - name: youtube-transcript-db
    databaseName: youtube_transcript
    user: admin